services:
  app:
    container_name: app
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
    depends_on:
      - db
    networks:
      - oaktechtest-net

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oaktechtest
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - oaktechtest-net

networks:
  oaktechtest-net:
    external: true
    name: oaktechtest-net

volumes:
  mysql_data: