services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/var/html/www"
    depends_on:
      - db
    # networks:
    #   - internal

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: oaktechtest
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    # networks:
    #   - internal

volumes:
  mysql_data: